// ============================================================
// PRODUKTE HIER PFLEGEN
// ============================================================
// WICHTIG:
// 1) Deine Amazon Partner-ID wird EINMAL in settings.js eingetragen.
// 2) Ist eine ASIN vorhanden, erzeugt product-utils.js daraus automatisch den Partnerlink.
// 3) affiliateUrl ist optional und überschreibt den automatisch erzeugten Link (z. B. SiteStripe).
// 4) amazonUrl ist der neutrale Produkt-/Suchlink als Fallback.
// 5) Preise/Bewertungen werden NICHT auf der Website angezeigt, weil sie sich ändern.
// 6) imageUrl ist für eine von Amazon bereitgestellte bzw. anderweitig zulässig nutzbare Bild-URL.
//    Amazon-Produktbilder nicht einfach herunterladen und ins Repository kopieren.
// 7) Ist imageUrl leer oder kann das Bild nicht geladen werden, zeigt die Seite automatisch
//    einen neutralen Marken-Platzhalter.
//
// Die Felder research.* sind nur deine interne Recherchehilfe und werden nicht angezeigt.

window.PRODUCTS = [
  {
    id: "ninja-af400eu",
    title: "Ninja Foodi MAX Dual Zone AF400EU",
    brand: "Ninja",
    category: "Küche",
    description: "Große Dual-Zone-Heißluftfritteuse für zwei Speisen mit getrennten Garbereichen – interessant für Familien und größere Portionen.",
    highlights: ["2 getrennte Garzonen", "Großes Fassungsvermögen", "Hohe Nachfrage"],
    badge: "Top-Auswahl",
    priority: "A",
    asin: "B09DGBJN2C",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B09DGBJN2C",
    imageUrl: "",
    articleSlugs: ["praktische-kuechenhelfer", "geschenkideen-zuhause"],
    research: { priceRange: "ca. 100–170 €", ratingSnapshot: "4,7/5", reviewCountSnapshot: "8.000+", checked: "August 2026" }
  },
  {
    id: "cosori-dual-zone",
    title: "COSORI Dual Zone 8,5 L",
    brand: "COSORI",
    category: "Küche",
    description: "Dual-Basket-Airfryer mit großem Gesamtvolumen – geeignet, wenn Hauptgericht und Beilage parallel zubereitet werden sollen.",
    highlights: ["Dual Basket", "8,5 Liter", "Beliebte Airfryer-Kategorie"],
    badge: "Beliebt",
    priority: "A",
    asin: "B0CHB7TNWH",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B0CHB7TNWH",
    imageUrl: "",
    articleSlugs: ["praktische-kuechenhelfer", "geschenkideen-zuhause"],
    research: { priceRange: "ca. 110–140 €", ratingSnapshot: "4,8/5", reviewCountSnapshot: "200+", checked: "August 2026" }
  },
  {
    id: "cosori-turboblaze",
    title: "COSORI TurboBlaze 6 L",
    brand: "COSORI",
    category: "Küche",
    description: "Kompaktere 6-Liter-Heißluftfritteuse mit viel Nutzvolumen bei moderater Stellfläche – passend für kleinere Küchen.",
    highlights: ["6 Liter", "Kompakter als Dual-Zone", "Vielseitige Programme"],
    badge: "Kleine Küche",
    priority: "A",
    asin: "B0CX8W9ZGF",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B0CX8W9ZGF",
    imageUrl: "",
    articleSlugs: ["praktische-kuechenhelfer", "kleine-kueche"],
    research: { priceRange: "ca. 110–140 €", ratingSnapshot: "4,8/5", reviewCountSnapshot: "900+", checked: "August 2026" }
  },
  {
    id: "bosch-ergomixx-msm67170",
    title: "Bosch ErgoMixx MSM67170",
    brand: "Bosch",
    category: "Küche",
    description: "Stabmixer-Set für Suppen, Saucen, Dips und kleinere Zerkleinerungsaufgaben – ein vielseitiger Küchenhelfer ohne viel Stellfläche.",
    highlights: ["Stabmixer-Set", "Kompakt verstaubar", "Bekannte Marke"],
    badge: "Allrounder",
    priority: "A",
    asin: "B009W0L6KM",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B009W0L6KM",
    imageUrl: "",
    articleSlugs: ["praktische-kuechenhelfer", "kleine-kueche"],
    research: { priceRange: "ca. 50–70 €", ratingSnapshot: "4,7/5", reviewCountSnapshot: "2.300+", checked: "August 2026" }
  },
  {
    id: "bialetti-moka-express",
    title: "Bialetti Moka Express 6 Tassen, Rot",
    brand: "Bialetti",
    category: "Küche",
    description: "Klassischer Espressokocher für den Herd – kompakt, langlebig und als Einstieg in die Kaffee-Routine gut verständlich.",
    highlights: ["Klassischer Espressokocher", "Kompakte Bauform", "Sehr viele Bewertungen"],
    badge: "Kaffee-Klassiker",
    priority: "A",
    asin: "B071CGGMRG",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B071CGGMRG",
    imageUrl: "",
    articleSlugs: ["kaffee-zuhause", "kleine-kueche", "geschenkideen-zuhause"],
    research: { priceRange: "ca. 20–45 € je Größe", ratingSnapshot: "4,7/5", reviewCountSnapshot: "10.000+", checked: "August 2026" }
  },
  {
    id: "wmf-stelio-milchaufschaeumer",
    title: "WMF Stelio Milchaufschäumer",
    brand: "WMF",
    category: "Küche",
    description: "Elektrischer Milchaufschäumer für Cappuccino, Latte oder Kakao – eine unkomplizierte Ergänzung für die tägliche Kaffee-Routine.",
    highlights: ["Elektrisch", "Kompakte Bauform", "Kaffee-Zubehör"],
    badge: "Kaffee",
    priority: "A",
    asin: "B07N7V3B8C",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B07N7V3B8C",
    imageUrl: "",
    articleSlugs: ["kaffee-zuhause", "praktische-kuechenhelfer", "geschenkideen-zuhause"],
    research: { priceRange: "ca. 45–60 €", ratingSnapshot: "4,2/5", reviewCountSnapshot: "300+", checked: "August 2026" }
  },
  {
    id: "zwilling-enfinigy-milchaufschaeumer",
    title: "ZWILLING Enfinigy Milchaufschäumer, Silber",
    brand: "ZWILLING",
    category: "Küche",
    description: "Designorientierter elektrischer Milchaufschäumer für warme und kalte Milchschaum-Varianten.",
    highlights: ["Warm & kalt", "Designorientiert", "Geschenkgeeignet"],
    badge: "Geschenkidee",
    priority: "A",
    asin: "B09MMH65B3",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B09MMH65B3",
    imageUrl: "",
    articleSlugs: ["kaffee-zuhause", "geschenkideen-zuhause"],
    research: { priceRange: "ca. 60–90 €", ratingSnapshot: "4,3/5", reviewCountSnapshot: "600+", checked: "August 2026" }
  },
  {
    id: "logitech-mx-master-3s",
    title: "Logitech MX Master 3S, Graphit",
    brand: "Logitech",
    category: "Homeoffice",
    description: "Ergonomisch geformte Produktivitätsmaus mit zusätzlichen Tasten und präzisem Scrollrad – besonders interessant für lange Arbeitstage.",
    highlights: ["Ergonomische Form", "Produktivitätsfunktionen", "Multi-Device"],
    badge: "Homeoffice-Favorit",
    priority: "A",
    asin: "B07W5JKHFZ",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B07W5JKHFZ",
    imageUrl: "",
    articleSlugs: ["homeoffice-helfer", "schreibtisch-ordnung", "geschenkideen-zuhause"],
    research: { priceRange: "ca. 80–110 €", ratingSnapshot: "4,6/5", reviewCountSnapshot: "1.400+", checked: "August 2026" }
  },
  {
    id: "logitech-lift",
    title: "Logitech Lift, Graphit",
    brand: "Logitech",
    category: "Homeoffice",
    description: "Vertikale Funkmaus für Nutzer, die eine alternative Handhaltung am Schreibtisch bevorzugen.",
    highlights: ["Vertikale Form", "Kabellos", "Leiser Klick"],
    badge: "Ergonomie",
    priority: "A",
    asin: "B07W4DGC27",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B07W4DGC27",
    imageUrl: "",
    articleSlugs: ["homeoffice-helfer", "schreibtisch-ordnung"],
    research: { priceRange: "ca. 45–65 €", ratingSnapshot: "4,7/5", reviewCountSnapshot: "700+ / modellabhängig deutlich mehr", checked: "August 2026" }
  },
  {
    id: "anker-737-powerbank",
    title: "Anker 737 Powerbank (PowerCore 24K)",
    brand: "Anker",
    category: "Technik",
    description: "Leistungsstarke USB-C-Powerbank für Smartphone, Tablet und kompatible Notebooks – ein höherpreisiger Technikartikel mit breitem Einsatzgebiet.",
    highlights: ["Hohe Ladeleistung", "USB-C", "Auch für viele Notebooks"],
    badge: "Top-Auswahl",
    priority: "A",
    asin: "B09VPHVT2Z",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B09VPHVT2Z",
    imageUrl: "",
    articleSlugs: ["technik-alltag", "usb-c-zubehoer", "homeoffice-helfer", "geschenkideen-zuhause"],
    research: { priceRange: "ca. 70–110 €", ratingSnapshot: "4,7/5", reviewCountSnapshot: "2.600+", checked: "August 2026" }
  },
  {
    id: "anker-nano-10000",
    title: "Anker Nano Powerbank 10.000 mAh, Blau",
    brand: "Anker",
    category: "Technik",
    description: "Kompakte 10.000-mAh-Powerbank für unterwegs – leichter zu transportieren als große Notebook-Powerbanks.",
    highlights: ["10.000 mAh", "Kompakt", "USB-C"],
    badge: "Unterwegs",
    priority: "A",
    asin: "B0C9CSG3B7",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B0C9CSG3B7",
    imageUrl: "",
    articleSlugs: ["technik-alltag", "usb-c-zubehoer", "geschenkideen-zuhause"],
    research: { priceRange: "ca. 30–45 €", ratingSnapshot: "4,8/5", reviewCountSnapshot: "200+", checked: "August 2026" }
  },
  {
    id: "ugreen-nexode-100w",
    title: "UGREEN Nexode 100 W GaN Ladegerät",
    brand: "UGREEN",
    category: "Technik",
    description: "Mehrport-GaN-Ladegerät für Smartphone, Tablet und kompatible Notebooks – ersetzt je nach Setup mehrere einzelne Netzteile.",
    highlights: ["Bis 100 W", "GaN", "Mehrere Anschlüsse"],
    badge: "USB-C",
    priority: "A",
    asin: "B091TV6LWN",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B091TV6LWN",
    imageUrl: "",
    articleSlugs: ["usb-c-zubehoer", "technik-alltag", "homeoffice-helfer", "schreibtisch-ordnung"],
    research: { priceRange: "ca. 35–60 €", ratingSnapshot: "4,7/5", reviewCountSnapshot: "400+", checked: "August 2026" }
  },
  {
    id: "ugreen-revodok-pro",
    title: "UGREEN Revodok Pro 106 USB-C Hub",
    brand: "UGREEN",
    category: "Technik",
    description: "Kompakter USB-C-Hub für zusätzliche Anschlüsse am Notebook – praktisch, wenn moderne Geräte nur wenige Ports bieten.",
    highlights: ["USB-C Hub", "Mehrere Ports", "Kompakt"],
    badge: "Preis-Leistung",
    priority: "A",
    asin: "B0D1XLNWP2",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B0D1XLNWP2",
    imageUrl: "",
    articleSlugs: ["usb-c-zubehoer", "homeoffice-helfer", "schreibtisch-ordnung", "technik-alltag"],
    research: { priceRange: "ca. 15–40 € je Variante", ratingSnapshot: "4,8/5", reviewCountSnapshot: "200+", checked: "August 2026" }
  },
  {
    id: "ugreen-usb-c-dock",
    title: "UGREEN Revodok Pro 2111 Dockingstation",
    brand: "UGREEN",
    category: "Homeoffice",
    description: "Docking-Lösung für Monitor, Peripherie und weitere Anschlüsse – sinnvoll für einen Arbeitsplatz, an dem das Notebook regelmäßig an- und abgedockt wird.",
    highlights: ["Dockingstation", "Notebook-Arbeitsplatz", "Weniger Kabelwechsel"],
    badge: "Homeoffice",
    priority: "A",
    asin: "B0DRNZFYC9",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B0DRNZFYC9",
    imageUrl: "",
    articleSlugs: ["homeoffice-helfer", "usb-c-zubehoer", "schreibtisch-ordnung"],
    research: { priceRange: "je Modell ca. 25–100+ €", ratingSnapshot: "4,7/5", reviewCountSnapshot: "300+", checked: "August 2026" }
  },
  {
    id: "tapo-p110",
    title: "TP-Link Tapo P110",
    brand: "TP-Link",
    category: "Smart Home",
    description: "WLAN-Steckdose zum Schalten und Automatisieren angeschlossener Geräte – günstiger Einstieg in Smart-Home-Automationen.",
    highlights: ["WLAN-Steckdose", "Zeitpläne", "Energie-Messfunktion modellabhängig"],
    badge: "Smart Home",
    priority: "A",
    asin: "B09BFT7NZJ",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B09BFT7NZJ",
    imageUrl: "",
    articleSlugs: ["technik-alltag", "wohnaccessoires", "geschenkideen-zuhause"],
    research: { priceRange: "ca. 10–20 € einzeln", ratingSnapshot: "4,6/5", reviewCountSnapshot: "600+", checked: "August 2026" }
  },
  {
    id: "philips-hue-smart-plug",
    title: "Philips Hue Smart Plug",
    brand: "Philips Hue",
    category: "Smart Home",
    description: "Schaltbare Steckdose für das Hue-Ökosystem – praktisch, um klassische Leuchten in Automationen einzubinden.",
    highlights: ["Hue-Integration", "Licht-Automation", "Einfache Nachrüstung"],
    badge: "Wohnen",
    priority: "A",
    asin: "",
    asinStatus: "Bitte per SiteStripe prüfen",
    manufacturerProductNumber: "929003050601",
    ean: "8719514342309",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/s?k=Philips+Hue+Smart+Plug+929003050601",
    imageUrl: "",
    articleSlugs: ["wohnaccessoires", "technik-alltag", "geschenkideen-zuhause"],
    research: { priceRange: "ca. 25–35 €", ratingSnapshot: "4,6/5", reviewCountSnapshot: "900+", checked: "August 2026" }
  },
  {
    id: "echo-dot",
    title: "Amazon Echo Dot (5. Generation), Anthrazit",
    brand: "Amazon",
    category: "Smart Home",
    description: "Kompakter Smart Speaker für Sprachsteuerung, Timer, Musik und kompatible Smart-Home-Geräte.",
    highlights: ["Alexa", "Smart-Home-Steuerung", "Kompakt"],
    badge: "Geschenkidee",
    priority: "A",
    asin: "B09B8X9RGM",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B09B8X9RGM",
    imageUrl: "",
    articleSlugs: ["technik-alltag", "wohnaccessoires", "geschenkideen-zuhause"],
    research: { priceRange: "stark aktionsabhängig", ratingSnapshot: "modellabhängig", reviewCountSnapshot: "sehr hohe Nachfrage", checked: "August 2026" }
  },
  {
    id: "fire-tv-stick-hd",
    title: "Amazon Fire TV Stick HD (2026)",
    brand: "Amazon",
    category: "Technik",
    description: "Streaming-Stick für Fernseher mit HDMI – ein leicht verständliches Technikprodukt mit breitem Einsatzgebiet.",
    highlights: ["Streaming", "HDMI", "Alexa-Sprachfernbedienung"],
    badge: "Streaming",
    priority: "A",
    asin: "B0DVJ64ZLT",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B0DVJ64ZLT",
    imageUrl: "",
    articleSlugs: ["technik-alltag", "geschenkideen-zuhause"],
    research: { priceRange: "aktionsabhängig", ratingSnapshot: "modellabhängig", reviewCountSnapshot: "hohe Nachfrage", checked: "August 2026" }
  },
  {
    id: "kindle-paperwhite",
    title: "Amazon Kindle Paperwhite 16 GB (12. Generation)",
    brand: "Amazon",
    category: "Technik",
    description: "E-Reader mit blendarmem Display und langer Akkulaufzeit – ein höherpreisiges Geschenkprodukt mit klarer Zielgruppe.",
    highlights: ["E-Ink Display", "Lange Akkulaufzeit", "Reisegeeignet"],
    badge: "Geschenkidee",
    priority: "A",
    asin: "B0CFPXBJ9Y",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B0CFPXBJ9Y",
    imageUrl: "",
    articleSlugs: ["technik-alltag", "geschenkideen-zuhause", "wohnaccessoires"],
    research: { priceRange: "ca. 150–200+ € je Modell", ratingSnapshot: "modellabhängig", reviewCountSnapshot: "hohe Nachfrage", checked: "August 2026" }
  },
  {
    id: "levoit-lvac-200",
    title: "Levoit LVAC-200 Akku-Staubsauger",
    brand: "Levoit",
    category: "Haushalt",
    description: "Kabelloser Akkusauger für die schnelle Boden- und Alltagsreinigung – interessant für Ordnungs- und Haushaltsinhalte.",
    highlights: ["Kabellos", "Schnelle Alltagsreinigung", "Haushalt"],
    badge: "Haushalt",
    priority: "A",
    asin: "B0DHZJVSYQ",
    asinStatus: "recherchiert",
    affiliateUrl: "",
    amazonUrl: "https://www.amazon.de/dp/B0DHZJVSYQ",
    imageUrl: "",
    articleSlugs: ["ordnung-zuhause", "wohnaccessoires"],
    research: { priceRange: "ca. 100–150 €", ratingSnapshot: "Recherchekandidat", reviewCountSnapshot: "Bestseller-/Nachfrageindikator", checked: "August 2026" }
  }
];
